# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_linkedlist.ipynb.

# %% auto 0
__all__ = ['ListNode', 'make_ll']

# %% ../nbs/00_linkedlist.ipynb 2
class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next
        
    def __str__(self):
        t = self.next
        _str = f"{self.val}-->"
        while t:
            _str += f"{t.val}-->"
            t = t.next
        return _str
    
    __repr__ = __str__

def make_ll(lst):
    lst = lst[::-1]
    head = ListNode(lst.pop())
    curr = head
    while lst:
        curr.next = ListNode(lst.pop())
        curr = curr.next
    return head
