# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_linkedlist.ipynb.

# %% auto 0
__all__ = ['ListNode', 'make_linked_list', 'reverse_linked_list']

# %% ../nbs/00_linkedlist.ipynb 3
class ListNode:
    def __init__(self, 
                 val: int, #Value of the node
                 next=None): #Pointer to the next node
        self.val = val
        self.next = next
        
    def __str__(self):
        t = self.next
        _str = f"{self.val}-->"
        while t:
            _str += f"{t.val}-->"
            t = t.next
        return _str
    
    __repr__ = __str__

# %% ../nbs/00_linkedlist.ipynb 4
def make_linked_list(lst):
    """
    This function takes in a list of integers and returns a head ptr of linked list `ListNode` 
    """
    lst = lst[::-1]
    head = ListNode(lst.pop())
    curr = head
    while lst:
        curr.next = ListNode(lst.pop())
        curr = curr.next
    return head


# %% ../nbs/00_linkedlist.ipynb 7
def reverse_linked_list(ll: ListNode):
    """
    For a given linked list, reverse the list and return it's head pointer
    """
    curr = ll
    prev = None
    while curr:
        t = curr.next
        curr.next = prev
        prev = curr
        curr = t
    return prev
